spring:
  datasource:
    url: jdbc:mysql://localhost:3306/community?serverTimezone=UTC&useSSL=false
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  config:
    import: optional:file:.env[.properties]

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: ture

  logging:
    level:
      org:
        springdoc: DEBUG
        springframework:
          web: DEBUG
          security: TRACE


# === JWT: 시크릿과 토큰 만료 시간 설정
jwt:
  secret: ${JWT_SECRET}
  access-expiration-ms: 1800000
  refresh-expiration-ms: 1209600000

# === AWS S3
cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ap-northeast-2
    s3:
      bucket: test-bucket
    stack:
      auto: false